### ISSUE TITLE
[$30] Errors in challenge forum processor log

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/forums#129]
@atelomycterus - Low priority, but I'm seeing some errors in the logs in dev:

```
2020-11-06T08:59:55.172Z [debug]: Message from challenge.notification.events: [{"type":"UPDATE_DRAFT_CHALLENGE","data":{"id":30057506,"confidentialityType":null,"technologies":[],"subTrack":"FIRST_2_FINISH","name":"sandy_forum_copilot","reviewType":"COMMUNITY","billingAccountId":null,"milestoneId":1,"detailedRequirements":"Test","submissionGuidelines":null,"registrationStartsAt":"2020-11-06T08:59:00.000Z","registrationEndsAt":"2020-11-16T08:59:00.000Z","checkpointSubmissionStartsAt":null,"checkpointSubmissionEndsAt":null,"submissionEndsAt":"2020-11-16T09:04:00.000Z","round1Info":null,"round2Info":null,"platforms":[{"id":2,"name":null}],"numberOfCheckpointPrizes":0,"checkpointPrize":0,"finalDeliverableTypes":null,"prizes":[100],"projectId":23745,"submissionVisibility":false,"maxNumOfSubmissions":0,"task":null,"assignees":null,"failedRegisterUsers":null,"copilotFee":null,"copilotId":null,"codeRepo":null,"environment":null,"fixedFee":null,"percentageFee":null},"userId":22838965}]
2020-11-06T08:59:55.172Z [info]: Getting M2M token for client ID=9eGR1ZKeWWgaqOxezpDG9X7p81ag88Pn
2020-11-06T08:59:55.282Z [error]: { Error: Bad Request
    at Request.callback (/challenge-forum-processor/node_modules/superagent/lib/node/index.js:871:15)
    at /challenge-forum-processor/node_modules/superagent/lib/node/index.js:1114:20
    at IncomingMessage.<anonymous> (/challenge-forum-processor/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  status: 400,
  response:
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res:
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 400,
        statusMessage: 'Bad Request',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        text: '{"id":"19c7a060:1759cbfaffc:-7e9e","result":{"success":true,"status":400,"metadata":null,"content":"Invalid value for \'id\': undefined"},"version":"v3"}',
        read: [Function] },
     request:
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        _enableHttp2: false,
        _agent: false,
        _formData: null,
        method: 'GET',
        url: 'https://api.topcoder-dev.com/v3/users?filter=id%3Dundefined',
        _header: [Object],
        header: [Object],
        writable: true,
        _redirects: 0,
        _maxRedirects: 5,
        cookies: '',
        qs: {},
        _query: [],
        qsRaw: [],
        _redirectList: [],
        _streamRequest: false,
        req: [Object],
        protocol: 'https:',
        host: 'api.topcoder-dev.com',
        _endCalled: true,
        _callback: [Function],
        _fullfilledPromise: [Object],
        res: [Object],
        _resBuffered: true,
        response: [Circular],
        called: true },
     req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /v3/users?filter=id%3Dundefined HTTP/1.1\r\nHost: api.topcoder-dev.com\r\nAccept-Encoding: gzip, deflate\r\nAuthorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik5VSkZORGd4UlRVME5EWTBOVVkzTlRkR05qTXlRamxETmpOQk5UYzVRVUV3UlRFeU56TTJRUSJ9.eyJpc3MiOiJodHRwczovL3RvcGNvZGVyLWRldi5hdXRoMC5jb20vIiwic3ViIjoiOWVHUjFaS2VXV2dhcU94ZXpwREc5WDdwODFhZzg4UG5AY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vbTJtLnRvcGNvZGVyLWRldi5jb20vIiwiaWF0IjoxNjA0NjM4MDE3LCJleHAiOjE2MDQ3MjQ0MTcsImF6cCI6IjllR1IxWktlV1dnYXFPeGV6cERHOVg3cDgxYWc4OFBuIiwic2NvcGUiOiJhbGw6Y2hhbGxlbmdlcyByZWFkOmNoYWxsZW5nZXMgd3JpdGU6Y2hhbGxlbmdlcyB3cml0ZTpncm91cHMgcmVhZDpncm91cHMgcmVhZDpwcm9qZWN0IHJlYWQ6dXNlcl9wcm9maWxlcyByZWFkOnJvbGVzIHJlYWQ6cHJvamVjdC11c2VyIHJlYWQ6cmVzb3VyY2VzIHJlYWQ6dGVybXMgcmVhZDpwcm9qZWN0cyByZWFkOnByb2plY3QtbWVtYmVycyByZWFkOmdyb3VwIGNyZWF0ZTpjaGFsbGVuZ2VzIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.MoGZNGMugvd80uzGeHF3O-S7c5-FgQABILgrPRtFM9kv3j2JV2eL47sziFgYJ_8zrSIuL1LzJ0nepZ3CBCkq5nWTRxjno7MQQS0WE6jOZK9iuuF4wbg6S-CiF8k1k72CTddL-w_e2Tv6HXzvOVz6py3X9Q56L5CkEcI5bGFPxl7jcstwg3WP1lZ63qviMrOFGk5oUx5yzd6ihkCbROKYdG2BfaMBOVbV9O6O_CyFXnTJQbT_QMUz00UbuBB3w010lX78yGcDLYewUOqq6gL6jSnErN2SrRRgYiTjq3UqQ8rMpT8FAO1wwxUby5g-cTdMPF6RF5jN9AK6VQ_337oD4A\r\nContent-Type: application/json\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/v3/users?filter=id%3Dundefined',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     text: '{"id":"19c7a060:1759cbfaffc:-7e9e","result":{"success":true,"status":400,"metadata":null,"content":"Invalid value for \'id\': undefined"},"version":"v3"}',
     body:
      { id: '19c7a060:1759cbfaffc:-7e9e',
        result: [Object],
        version: 'v3' },
     files: undefined,
     buffered: true,
     headers:
      { date: 'Fri, 06 Nov 2020 08:59:55 GMT',
        'content-type': 'application/json',
        'content-length': '151',
        connection: 'close',
        server: 'nginx',
        'access-control-allow-headers': 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since',
        'access-control-allow-credentials': 'true',
        'access-control-allow-methods': 'GET, POST, OPTIONS, DELETE, PUT, PATCH' },
     header:
      { date: 'Fri, 06 Nov 2020 08:59:55 GMT',
        'content-type': 'application/json',
        'content-length': '151',
        connection: 'close',
        server: 'nginx',
        'access-control-allow-headers': 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since',
        'access-control-allow-credentials': 'true',
        'access-control-allow-methods': 'GET, POST, OPTIONS, DELETE, PUT, PATCH' },
     statusCode: 400,
     status: 400,
     statusType: 4,
     info: false,
     ok: false,
     redirect: false,
     clientError: true,
     serverError: false,
     error:
      { Error: cannot GET /v3/users?filter=id%3Dundefined (400)
    at Response.toError (/challenge-forum-processor/node_modules/superagent/lib/node/response.js:98:13)
    at ResponseBase._setStatusProperties (/challenge-forum-processor/node_modules/superagent/lib/response-base.js:119:48)
    at new Response (/challenge-forum-processor/node_modules/superagent/lib/node/response.js:44:8)
    at Request._emitResponse (/challenge-forum-processor/node_modules/superagent/lib/node/index.js:918:18)
    at /challenge-forum-processor/node_modules/superagent/lib/node/index.js:1114:42
    at IncomingMessage.<anonymous> (/challenge-forum-processor/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
        status: 400,
        text: '{"id":"19c7a060:1759cbfaffc:-7e9e","result":{"success":true,"status":400,"metadata":null,"content":"Invalid value for \'id\': undefined"},"version":"v3"}',
        method: 'GET',
        path: '/v3/users?filter=id%3Dundefined' },
     created: false,
     accepted: false,
     noContent: false,
     badRequest: true,
     unauthorized: false,
     notAcceptable: false,
     forbidden: false,
     notFound: false,
     unprocessableEntity: false,
     type: 'application/json',
     links: {},
     setEncoding: [Function: bound ],
     redirects: [],
     pipe: [Function] } }
```

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30149323 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30149323 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment]
@jmgasper  The challenge forum processor handles only  "USER_REGISTRATION","USER_UNREGISTRATION" from 'challenge.notification.events'. 

```
Message from challenge.notification.events: [{"type":"UPDATE_DRAFT_CHALLENGE",...
```

Challenge forum processor: 
"challenge.notification.create" - create a group and other Vanilla entities
"challenge.notification.update" - update group's name + root category's name
"challenge.notification.events" - "USER_REGISTRATION","USER_UNREGISTRATION" - register/unregister user

Now it throws an error if a message couldn't be processed (PR- https://github.com/topcoder-platform/challenge-forum-processor/pull/38) 
![image](https://user-images.githubusercontent.com/10196632/98355778-afd00a80-2033-11eb-91ef-6578084c19f7.png)

If we need to process this type of messages let me know.

**Comment by jmgasper** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30149323<br/><br/>```This is an automated message for ghostar via Topcoder X```
