### ISSUE TITLE
[$700] Groups investigation

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/forums#18]
-- Payment will be applied here shortly.  Just double checking the billing account setup before I create the challenge.

@atelomycterus - We are working with Vanilla to evaluate a hosted solution from them, instead of self hosting.  

One thing I'd like to do is update the challenge forum processor to use groups instead of custom roles.

### Branch

Please target the `vanilla-groups` branch for the work

### Vanilla

Our test vanilla installation is here:

* Website:   https://topcoder.vanillacommunity.com/

I'll email you an admin username / password

You can find the groups API in the dashboard, under `API`:

![Screen Shot 2020-08-14 at 09 54 34](https://user-images.githubusercontent.com/21790/90198161-29c96c80-de14-11ea-9b61-2ce14ebe321a.png)

### Requirements

I'm hoping the Groups functionality can replace the custom roles that we create for each and every challenge currently.

* For each challenge, we'll create a Group.  
  * The group will be secret
  * The current `Welcome!` text will be the description of the group.  - `Any questions related to this challenge....`
  * Registered members for the challenge will be invited to me group
  * If a user unregisters, they will be removed from the group
* There will be one initial discussion called `Code Documents`.
* There will be an announcement that has the phase deadlines and a link back to OR for submission
* There will be events set up for the individual phases

### Screenshots

![Screen Shot 2020-08-14 at 09 59 21](https://user-images.githubusercontent.com/21790/90198378-d99eda00-de14-11ea-821a-3385f954bf1a.png)

![Screen Shot 2020-08-14 at 09 58 46](https://user-images.githubusercontent.com/21790/90198396-e1f71500-de14-11ea-813c-31c3c44489b7.png)

**Comment by atelomycterus** [comment]
@jmgasper, Hi! Ok, I understand the task. I haven't received any emails from you. Please re-send an admin username / password and I'll start working on it.
My email  is o_bogdanova@inbox.ru

**Comment by atelomycterus** [comment]
@jmgasper Some questions about Topcoder categories.  I have looked through the current code base + API v2. With Group functionality, creating a sub-category with challenge names (which is used as a workaround) underneath Topcoder categories is redundant.

But what about using Topcoder categories? Are there any requirements? 
The discussions can be assigned to a group and a category. There are two independent fields.
Adding a discussion '/discussions':
```
{
  "body": "string",
  "categoryID": 0,
  "closed": true,
  "format": "markdown",
  "groupID": 0,
  "name": "string",
  "pinLocation": "category",
  "pinned": true,
  "sink": true
}
```

1. Should we assign a Topcoder category to a discussion?

For example, a development challenge 'Challenge 1':
 - a new group is created 
 - all group's discussions  will be assigned to this group and the 'Development Forums' category. 

Using default categories help to filter discussions by category (/discussions) or search discussions (/discussions/search) to limit search results to.

2. Shall I create these Topcoder categories in test Vanilla?

**Comment by jmgasper** [comment]
1.  I don't think we need to assign the category for now - just the group will be enough.  We can mess with that later, but I'm most concerned right now about making sure we can create the group, assign members, and that the group is properly secured for only those who have rights to it.

**Comment by atelomycterus** [comment]
@jmgasper  I see.  I have some questions:

### Events
> There will be events set up for the individual phases

We'll create an event for each phase. Please correct me if I am wrong.

### Adding/removing users to/from a group

Previously, we saved challengeId as a role's urlencode and could easily find the corresponding role.

There are approaches to implement adding/removing users to/from a group:
  1. Challenge name is used as a group's name.  Need to call Topcoder API to get challenge data by challengeId.
    Then find a group by challenge's name. Which Topcoder Challenge API and credentials should be used? 
    We use '/v3/users' to get user data.
	
 2. Create a plugin. The plugin basically has to do two things: create a new field in the database and extend the view accordingly.
    ChallengeId will be saved during creating a group. Can we upload a plugin if we use a hosted solution?
	
 3. We can keep challengeId as a part of a group name. The group name will be '{challengeId}-{challengeName}'.  So admin shouldn't rename groups.

We can implement the approach 3 quickly and test security.  I am planning to test and commit it tomorrow.


### Source
> we can create the group, assign members, and that the group is properly secured for only those who have rights to it.

Do they  provide access to the source code?

**Comment by jmgasper** [comment]
1.   Correct, an event for each phase

2.  For the add / remove users, let's go with option 3, if that's easiest.  We will *not* be able to upload a plugin at this time - that's a sticking point we identified on our call with them yesterday.  We're working with them to figure out a solution.

3.  For the source, we do not have access.  All we have is the API documentation.

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30137215 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30137215 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment]
@jmgasper Implemented the task but I can test it fully . I got the same error 'UnknownError' https://github.com/topcoder-platform/challenge-forum-processor/issues/17#issuecomment-618200204.

 Could you provide Topcoder  creds for Auth0?  

```
2020-08-15T13:01:32.565Z [debug]: Message from challenge.notification.events: [{"type":"USER_REGISTRATION","data":{"challengeId":"d28f85e8-1fa1-43d1-8fee-a44119ccee55","userId":151743}}]
2020-08-15T13:01:34.712Z [error]: Error: Unknown Error
    at Request._callback (/home/ubog/topcoder/vanilla/challenge-forum-processor/node_modules/tc-core-library-js/lib/auth/m2m.js:70:24)
    at Request.self.callback (/home/ubog/topcoder/vanilla/challenge-forum-processor/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/ubog/topcoder/vanilla/challenge-forum-processor/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/ubog/topcoder/vanilla/challenge-forum-processor/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by atelomycterus** [comment]
Current Status: Need to test it with Topcoder creds. After testing, I'll create PR. 
Source Code:  https://github.com/topcoder-platform/challenge-forum-processor/tree/vanilla-groups-issues-18

### Creating Groups and related entities

Using sample-data/challenge.notification.create.json:
1. Creating a group:
![image](https://user-images.githubusercontent.com/10196632/90315356-941d0280-df23-11ea-8aef-12e5172e8299.png)

2. Creating Announcements and Code Documents discussions:
![image](https://user-images.githubusercontent.com/10196632/90315363-a139f180-df23-11ea-8b79-332b8fc36ed1.png)

3. Creating Events. 'Upcoming Events' is empty if the phase dates have already passed.

Click on 'All Events':
![image](https://user-images.githubusercontent.com/10196632/90315424-2ae9bf00-df24-11ea-9b90-215597c47cc9.png)

Then click on 'All':
![image](https://user-images.githubusercontent.com/10196632/90315440-46ed6080-df24-11ea-8033-2ec83e99919f.png)

![image](https://user-images.githubusercontent.com/10196632/90315372-b31b9480-df23-11ea-8f0a-468246bc5928.png)


### Testing
1. Get the branch
2. Configure Vanilla env params  and Topcoder env params in challenge-forum-processor/config/default.js or set env vars.

**VANILLA_API_URL**='https://topcoder.vanillacommunity.com/api/v2'
**VANILLA_ADMIN_ACCESS_TOKEN**=<generate VANILLA_ADMIN_ACCESS_TOKEN on https://topcoder.vanillacommunity.com/profile/tokens>

**Comment by jmgasper** [comment]
@atelomycterus - This looks great, thanks!  Which creds do you need exactly?  The M2M ones?

For dev and an admin account, `TonyJ` / `appirio123` should work fine.

**Comment by atelomycterus** [comment]
@jmgasper I need Topcoder creds (see challenge-forum-processor/config/default.js) to  test user registration/unregistration events ("topic": "challenge.notification.events") . 
```
TOPCODER: {
    AUTH0_AUDIENCE: process.env.TOPCODER_AUTH0_AUDIENCE,
    AUTH0_CLIENT_ID: process.env.TOPCODER_AUTH0_CLIENT_ID,
    AUTH0_CLIENT_SECRET: process.env.TOPCODER_AUTH0_CLIENT_SECRET,
    AUTH0_PROXY_SERVER_URL: process.env.TOPCODER_AUTH0_PROXY_SERVER_URL,
    AUTH0_URL: process.env.TOPCODER_AUTH0_URL,
    API_URL: process.env.TOPCODER_API_URL || 'https://api.topcoder-dev.com',
    ROOT_URL: process.env.TOPCODER_ROOT_URL || 'https://topcoder-dev.com'
  }
```

I tested  only using sample-data/challenge.action.resource.create.json and sample-data/challenge.action.resource.delete.json. 
I created PR https://github.com/topcoder-platform/challenge-forum-processor/pull/25. Please apply it. Thanks!

### Adding/removing an user
> Registered members for the challenge will be invited to me group

Before testing change email for TonyJ account to receive an invitation email in your email box. 

_Developer Notes_
There are 2 methods to add an user to group:
 - Using invitation. Email will be sent to user. User should click on the link to join the group. 
 - Add user to a group without sending any emails.   If you want this one, let me know.

Group roles: leader and member. All users invited will have member role by default.

Invitation email:
![image](https://user-images.githubusercontent.com/10196632/90327799-09c6b400-dfa0-11ea-927c-6d86f6e88f51.png)

Sign in using Tony account (TonyJ / appirio123).

TonyJ's Notifications :
![image](https://user-images.githubusercontent.com/10196632/90327841-4a263200-dfa0-11ea-82ab-0b153c46dc25.png)

TonyJ's Groups: 
![image](https://user-images.githubusercontent.com/10196632/90327858-64601000-dfa0-11ea-802b-63880534c271.png)


Admin's view:
![image](https://user-images.githubusercontent.com/10196632/90327902-9d988000-dfa0-11ea-8090-820ac4650d75.png)

Admin can see all members:
![image](https://user-images.githubusercontent.com/10196632/90327911-b143e680-dfa0-11ea-97ff-3bdfc91e2ae3.png)

**Comment by jmgasper** [comment]
@atelomycterus - Thanks for that.  I'm still working with Topcoder to get you the configuration details.  I should have that for you soon.

**Comment by atelomycterus** [comment]
@jmgasper  I got 403 error (Forbidden)  with new creds:

The request url:  'https://api.topcoder-dev.com/v3/users?filter=id%3D88770043'
```
2020-08-17T05:35:55.470Z [debug]: Message from challenge.notification.events: [{"type":"USER_REGISTRATION","data":{"challengeId":"d28f85e8-1fa1-43d1-8fee-a44119ccee55","userId":88770043}}]

2020-08-17T05:35:57.534Z [error]: { Error: Forbidden
    at Request.callback (/home/ubog/topcoder/vanilla/challenge-forum-processor/node_modules/superagent/lib/node/index.js:871:15)
    at /home/ubog/topcoder/vanilla/challenge-forum-processor/node_modules/superagent/lib/node/index.js:1114:20
    at IncomingMessage.<anonymous> (/home/ubog/topcoder/vanilla/challenge-forum-processor/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at Stream.emit (events.js:198:13)
    at Unzip.<anonymous> (/home/ubog/topcoder/vanilla/challenge-forum-processor/node_modules/superagent/lib/node/unzip.js:53:12)
    at Unzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 403,
```

**Comment by jmgasper** [comment]
@atelomycterus - I see the same in my testing - checking with Topcoder on this...

**Comment by jmgasper** [comment]
@atelomycterus - Got this updated.  From Topcoder:

That auth0 key only has access to read and write groups.

I’ve added a bunch of read scopes that I think are relevant. If you can’t make other calls, please send me the API calls so I can line up the right scopes:

`"scope": "read:challenges write:groups read:groups read:project read:user_profiles read:project-user read:resources read:terms read:project-members read:group"`

**Comment by atelomycterus** [comment]
@jmgasper  See  the same error. The 'challenge.notification.events' payload contains userId. We need to get the user's handle by given the userId.  https://api.topcoder-dev.com/v3/users is used to get user handle. 
```
"payload": {
    "type": "USER_REGISTRATION",
    "data": {
      "challengeId": "d28f85e8-1fa1-43d1-8fee-a44119ccee55",
      "userId": 88770043
    }
```

**Comment by jmgasper** [comment]
@atelomycterus - Are you sure that the token is being set properly?  I was able to generate an M2M token and use it in Postman to make this call:

![Screen Shot 2020-08-19 at 08 17 20](https://user-images.githubusercontent.com/21790/90571084-691d0200-e1f4-11ea-9382-40c5bbec6802.png)

**Comment by atelomycterus** [comment]
@jmgasper Thanks! It was my fault. It works, no changes in code and ready for your review.

![image](https://user-images.githubusercontent.com/10196632/90597167-30cbf280-e1f9-11ea-8a7f-8014b798ed79.png)

**Comment by jmgasper** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30137215<br/><br/>```This is an automated message for ghostar via Topcoder X```
