### ISSUE TITLE
[$60] CI/CD investigation

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/forums#27]
@atelomycterus - Here's what we've figured out with CI/CD.  Comes down to the healthcheck that we add:

Ok. I think I figured it out. When you launch the server, it is “not configured”, meaning it does not have an .htaccess that rewrites. The Health check is set up to check / on the server, which before the .htaccess is in place, returns with a 200. 

When you configure the site, enabling the vanilla .htaccess, / then causes a redirect or doesn’t return what the health check is looking for, so ECS thinks it’s down and kicks it over.

Can we do one or a couple of these things:
* Figure out how we can deploy and not get that setup screen?
* Deploy our own .htaccess during the build process?
* Enable a rewrite condition in the .htaccess file as commented here https://github.com/vanilla/vanilla/blob/master/.htaccess.dist#L29 and provide a /health.php that returns a 200 so we can update the ECS health check?

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30140383 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30140383 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment]
@jmgasper Implemented. PR-https://github.com/topcoder-platform/forums/pull/29. Thanks!

1. Added .htaccess. If you need to return a specified response let me know. Now it returns the simple message ("succeess") for /health.php
![image](https://user-images.githubusercontent.com/10196632/92127258-cd051480-ee09-11ea-94e0-e9568c9577da.png)

2. Vanilla checks 'conf/config.php'. If the file doesn't exist then the setup page is displayed.
I added 'conf/config.php' with the default settings obtained after the first installation. This file is copied during a container building.

DB settings are saved in conf/config.php. So you need to set env params in vanilla.env:
MYSQL_HOST=
MYSQL_DATABASE=
MYSQL_ROOT_USER=
MYSQL_ROOT_PASSWORD=
 
3. Several things we should keep in mind:

a. Installation Vanilla. 
For the first installation of Vanilla, the 'conf/config.php' file does not need to be copied. It can be automated with an additional parameter. Let me know if it's required.

b. Vanilla saves the settings in a file, and some in the database. The list of params which saved in a file are attached. 
[config-defaults.php.txt](https://github.com/topcoder-platform/forums/files/5169295/config-defaults.php.txt)

If Vanilla Admin changes the settings (e.g. change a theme, enable/disable plugins, 
settings of some plugins or Vanilla settings) that are saved in the file, we can lose them after deployment (rebuilding a container). So we need to sync 'conf/config.php'  with the version in the repo.

c. Some values are auto-generated during Vanilla installation.  Let me know if some params should be  as env parameters in config.php for security reasons:
For example:
$Configuration['Garden']['Cookie']['Salt'] = 'rLpGSLgZD1AGdJ4n'; 
$Configuration['Garden']['UpdateToken'] = 'c3988cd76f721f1a03d2c347ab6655609a548425';

**Comment by jmgasper** [comment]
@atelomycterus - Thanks, I've documented this for the Topcoder ops team and we'll test it out and see.

**Comment by jmgasper** [comment]
@atelomycterus - This is all deployed, thanks.  It seems to be working better, but we're seeing this in the logs, related to that config file:
```
[04-Sep-2020 05:49:42] WARNING: [pool www] child 120 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Exception: Unable to write to config file '/vanillapp/conf/config.php' when saving. in /vanillapp/library/core/class.configurationsource.php:495"
[04-Sep-2020 05:49:42] WARNING: [pool www] child 120 said into stderr: "Stack trace:"
[04-Sep-2020 05:49:42] WARNING: [pool www] child 120 said into stderr: "#0 /vanillapp/library/core/class.configurationsource.php(593): Gdn_ConfigurationSource->save()"
[04-Sep-2020 05:49:42] WARNING: [pool www] child 120 said into stderr: "#1 /vanillapp/library/core/class.configuration.php(945): Gdn_ConfigurationSource->shutdown()"
[04-Sep-2020 05:49:42] WARNING: [pool www] child 120 said into stderr: "#2 /vanillapp/library/core/class.configuration.php(954): Gdn_Configuration->shutdown()"
[04-Sep-2020 05:49:42] WARNING: [pool www] child 120 said into stderr: "#3 [internal function]: Gdn_Configuration->__destruct()"
[04-Sep-2020 05:49:42] WARNING: [pool www] child 120 said into stderr: "#4 {main}"
[04-Sep-2020 05:49:42] WARNING: [pool www] child 120 said into stderr: "  thrown in /vanillapp/library/core/class.configurationsource.php on line 495"
[Fri Sep 04 05:49:42.328539 2020] [proxy_fcgi:error] [pid 61:tid 139985390921472] [client 10.15.135.141:7530] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: Unable to write to config file '/vanillapp/conf/config.php' when saving. in /vanillapp/library/core/class.configurationsource.php:495\nStack trace:\n#0 /vanillapp/library/core/class.configurationsource.php(593): Gdn_ConfigurationSource->save()\n#1 /vanillapp/library/core/class.configuration.php(945): Gdn_ConfigurationSource->shutdown()\n#2 /vanillapp/library/core/class.configuration.php(954): Gdn_Configuration->shutdown()\n#3 [internal function]: Gdn_Configuration->__destruct()\n#4 {main}\n  thrown in /vanillapp/library/core/class.configurationsource.php on line 495\n', referer: https://vanilla.topcoder-dev.com/
```

**Comment by atelomycterus** [comment]
@jmgasper Fixed permissions on config.php. It should be 775 for 'application'.  PR-https://github.com/topcoder-platform/forums/pull/30. 

From Vanilla code: 
```
 $tmpFile = tempnam(PATH_CONF, 'config');
                $result = false;
                if (file_put_contents($tmpFile, $fileContents) !== false) {
                    chmod($tmpFile, 0775);
                    $result = rename($tmpFile, $this->Source);
                }
```

**Comment by jmgasper** [comment]
Looks good now, thanks.  I'm going to close this out and will open up new ticket(s) if we need further changes.  We're still seeing an issue, but I think it's more a Topcoder setup problem than a problem with Vanilla.

**Comment by jmgasper** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30140383<br/><br/>```This is an automated message for ghostar via Topcoder X```
