### ISSUE TITLE
[$75] Forum processor issue

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/forums#405]
@atelomycterus - Reported by Topcoder:

I’m seeing this error in the forums-processor in prod

```
{ Error: cannot GET /v5/challenges/30166985 (404) (edited) 
```

Is there a call there that’s calling with a legacy id like that? that format won’t work

```
2021-02-16T03:12:37.739-05:00	method: 'GET',
2021-02-16T03:12:37.739-05:00	url: 'https://api.topcoder.com/v5/challenges/30166985',
```

**Comment by jmgasper** [comment]
Challenge https://www.topcoder.com/challenges/fbc24f20-103c-41be-9406-534ceb1edb60 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
@atelomycterus - Related to: https://github.com/topcoder-platform/forums/issues/404

**Comment by atelomycterus** [comment]
@jmgasper Could you provide the payload from a log file?

```
/**
 * Gets the challenge
 * @param {String} challengeId Challenge's ID (uuid)
 */
async function getChallenge (challengeId) {
  const path = `${config.TOPCODER.API_URL}/v5/challenges/${challengeId}`
  return reqToAPI('GET', path)
}
```

**Comment by jmgasper** [comment]
@atelomycterus - Working on it...

```
	2021-02-16T03:37:16.317-05:00	[33m2021-02-16T08:37:16.317Z[39m [[32minfo[39m]: Managing user for challengeID=9b362952-2383-44f1-8112-b06210e351c7 [action=invite, handle=aranjansenapati, projectRole=null, challengeRoles=["Reviewer"]]...
2021-02-16T03:37:16.430-05:00	[33m2021-02-16T08:37:16.430Z[39m [[31merror[39m]: Error: The group wasn't not found by challengeID
2021-02-16T03:37:16.430-05:00	at manageVanillaUser (/challenge-forum-processor/src/services/vanilla.js:28:11)
2021-02-16T03:37:16.430-05:00	at <anonymous>
2021-02-16T03:37:16.430-05:00	at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by jmgasper** [comment]
Also this:

```
2021-02-16T03:36:00.942-05:00	{ Error: cannot GET /api/v2/groups?access_token=va.5-CFmjqkQYPRUQiyMLOVNmY4r2bANepV.tzl9cg.zVbP16L&challengeID=30167490&page=1 (502)
2021-02-16T03:36:00.942-05:00	at Response.toError (/challenge-forum-processor/node_modules/superagent/lib/node/response.js:98:13)
2021-02-16T03:36:00.942-05:00	at ResponseBase._setStatusProperties (/challenge-forum-processor/node_modules/superagent/lib/response-base.js:119:48)
2021-02-16T03:36:00.942-05:00	at new Response (/challenge-forum-processor/node_modules/superagent/lib/node/response.js:44:8)
2021-02-16T03:36:00.942-05:00	at Request._emitResponse (/challenge-forum-processor/node_modules/superagent/lib/node/index.js:918:18)
2021-02-16T03:36:00.942-05:00	at IncomingMessage.<anonymous> (/challenge-forum-processor/node_modules/superagent/lib/node/index.js:1114:42)
2021-02-16T03:36:00.942-05:00	at emitNone (events.js:111:20)
2021-02-16T03:36:00.942-05:00	at IncomingMessage.emit (events.js:208:7)
2021-02-16T03:36:00.942-05:00	at endReadableNT (_stream_readable.js:1064:12)
2021-02-16T03:36:00.942-05:00	at _combinedTickCallback (internal/process/next_tick.js:139:11)
2021-02-16T03:36:00.942-05:00	at process._tickCallback (internal/process/next_tick.js:181:9)
2021-02-16T03:36:00.942-05:00	status: 502,
2021-02-16T03:36:00.942-05:00	text: '<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n',
2021-02-16T03:36:00.942-05:00	
```

**Comment by jmgasper** [comment]
```
2021-02-16T03:43:36.430-05:00	[33m2021-02-16T08:43:36.430Z[39m [[34mdebug[39m]: Message from challenge.action.resource.create: [{"id":"303ffef7-75dc-4c16-aeb7-f1cdbc416ea9","challengeId":"d1dd9219-ac97-4277-b802-4ca3cb2ccd42","memberId":"40029484","memberHandle":"jcori","roleId":"0e9c6879-39e4-4eb6-b8df-92407890faf1","created":"2021-02-16T08:43:35.000Z","createdBy":"yuTD2qvTb8e7KuqtT9vgEbI4yIJS7YhR@clients"}]
2021-02-16T03:43:36.430-05:00	[33m2021-02-16T08:43:36.430Z[39m [[34mdebug[39m]: Message from challenge.notification.create: [{"id":"d1dd9219-ac97-4277-b802-4ca3cb2ccd42","created":"2021-02-16T08:43:35.692Z","createdBy":"jcori","updated":"2021-02-16T08:43:35.692Z","updatedBy":"jcori","status":"New","projectId":24702,"name":"TEST CHALLENGE","typeId":"927abff4-7af9-4145-8ba1-577c16e64e2e","trackId":"9b6fc876-f4d9-4ccb-9dfd-419247628825","startDate":"2021-02-17T08:43:35.000Z","legacy":{"reviewType":"COMMUNITY"},"descriptionFormat":"markdown","timelineTemplateId":"7ebf1c69-f62f-4d3a-bdfb-fe9ddb56861c","terms":[{"id":"564a981e-6840-4a5c-894e-d5ad22e9cd6f","roleId":"732339e7-8e30-49d7-9198-cccf9451e221"}],"groups":["db53f15b-2d61-4d9e-8263-8cfc3f98337e"],"discussions":[{"name":"TEST CHALLENGE Discussion","type":"challenge","provider":"vanilla","id":"5cbf7968-3ff7-483b-8eb9-c83d1cbc5a6a"}],"description":"","phases":[{"phaseId":"a93544bc-c165-4af4-b55e-18f3593b457a","duration":432000,"id":"bfc5b5af-0b44-4b32-a06a-66b10a4f00a6","name":"Registration","isOpen":false,"scheduledStartDate":"2021-02-17T03:43:35-05:00","scheduledEndDate":"2021-02-22T08:43:35.000Z","actualStartDate":"2021-02-17T03:43:35-05:00","actualEndDate":"2021-02-22T08:43:35.000Z"},{"phaseId":"6950164f-3c5e-4bdc-abc8-22aaf5a1bd49","duration":432000,"id":"29f0931f-4117-4e6b-9963-e4bff8f487b3","name":"Submission","isOpen":false,"scheduledStartDate":"2021-02-17T03:43:35-05:00","scheduledEndDate":"2021-02-22T08:43:35.000Z","actualStartDate":"2021-02-17T03:43:35-05:00","actualEndDate":"2021-02-22T08:43:35.000Z"},{"phaseId":"aa5a3f78-79e0-4bf7-93ff-b11e8f5b398b","duration":172800,"id":"2c0a1c42-eb89-41b1-a860-598bd57436cd","name":"Review","isOpen":false,"predecessor":"29f0931f-4117-4e6b-9963-e4bff8f487b3","scheduledStartDate":"2021-02-22T08:43:35.000Z","scheduledEndDate":"2021-02-24T08:43:35.000Z","actualStartDate":"2021-02-22T08:43:35.000Z","actualEndDate":"2021-02-24T08:43:35.000Z"},{"phaseId":"1c24cfb3-5b0a-4dbd-b6bd-4b0dff5349c6","duration":43200,"id":"5ba3a4db-459e-43c9-b433-76a1ad442243","name":"Appeals","isOpen":false,"predecessor":"2c0a1c42-eb89-41b1-a860-598bd57436cd","scheduledStartDate":"2021-02-24T08:43:35.000Z","scheduledEndDate":"2021-02-24T20:43:35.000Z","actualStartDate":"2021-02-24T08:43:35.000Z","actualEndDate":"2021-02-24T20:43:35.000Z"},{"phaseId":"797a6af7-cd3f-4436-9fca-9679f773bee9","duration":57600,"id":"58619b2b-20b5-4757-8258-211d2a48494a","name":"Appeals Response","isOpen":false,"predecessor":"5ba3a4db-459e-43c9-b433-76a1ad442243","scheduledStartDate":"2021-02-24T20:43:35.000Z","scheduledEndDate":"2021-02-25T12:43:35.000Z","actualStartDate":"2021-02-24T20:43:35.000Z","actualEndDate":"2021-02-25T12:43:35.000Z"}],"endDate":"2021-02-25T12:43:35.000Z","numOfSubmissions":0,"numOfRegistrants":0,"currentPhaseNames":[],"registrationStartDate":"2021-02-17T03:43:35-05:00","registrationEndDate":"2021-02-22T08:43:35.000Z","submissionStartDate":"2021-02-17T03:43:35-05:00","submissionEndDate":"2021-02-22T08:43:35.000Z","track":"Development","type":"Challenge"}]
2021-02-16T03:43:36.431-05:00	[33m2021-02-16T08:43:36.431Z[39m [[32minfo[39m]: The challenge with challengeID=d1dd9219-ac97-4277-b802-4ca3cb2ccd42:
2021-02-16T03:43:36.558-05:00	[33m2021-02-16T08:43:36.557Z[39m [[32minfo[39m]: Managing user for challengeID=d1dd9219-ac97-4277-b802-4ca3cb2ccd42 [action=invite, handle=jcori, projectRole=null, challengeRoles=["Manager"]]...
2021-02-16T03:43:36.619-05:00	[33m2021-02-16T08:43:36.619Z[39m [[32minfo[39m]: Creating Vanilla entities for the 'TEST CHALLENGE Discussion' discussion ....
2021-02-16T03:43:36.664-05:00	[33m2021-02-16T08:43:36.664Z[39m [[31merror[39m]: Error: The group wasn't not found by challengeID
2021-02-16T03:43:36.664-05:00	at manageVanillaUser (/challenge-forum-processor/src/services/vanilla.js:28:11)
2021-02-16T03:43:36.664-05:00	at <anonymous>
2021-02-16T03:43:36.664-05:00	at process._tickCallback (internal/process/next_tick.js:189:7)
2021-02-16T03:43:36.747-05:00	[33m2021-02-16T08:43:36.747Z[39m [[32minfo[39m]: The group with groupID=490 was created
2021-02-16T03:43:41.945-05:00	[33m2021-02-16T08:43:41.945Z[39m [[32minfo[39m]: The 'TEST CHALLENGE' category was created
2021-02-16T03:43:46.924-05:00	[33m2021-02-16T08:43:46.924Z[39m [[32minfo[39m]: The 'Code Documents' category was created
2021-02-16T03:43:47.262-05:00	[33m2021-02-16T08:43:47.262Z[39m [[32minfo[39m]: The 'Challenge Overview' discussion/announcement was created
2021-02-16T03:43:47.575-05:00	[33m2021-02-16T08:43:47.575Z[39m [[32minfo[39m]: The 'Please give us feedback on this challenge!' discussion/announcement was created
```

**Comment by atelomycterus** [comment]
@jmgasper The original issues with challenge ID = `9ffff72c-ad6a-4c70-b0bf-ac52fd049558`. Could you try to search by 'Message from challenge.notification.create: [{"id":"9ffff72c-ad6a-4c70-b0bf-ac52fd049558"'? Thanks for your help!

![image](https://user-images.githubusercontent.com/10196632/108040301-32626000-704e-11eb-8d20-06bbcf82a568.png)

**Comment by atelomycterus** [comment]
@jmgasper Please remove access_token from urls before posting. I removed it from your comments.

1. I've reviewed the code of challenge processor, only 'challenge.id' is used , the value of challenge.id  not changed. challenge is a payload. If the challenge.id is number, not uuuid =>it throws  404 error. 

```
async function createVanillaGroup (challenge) {
  logger.info(`The challenge with challengeID=${challenge.id}:`)
  const { text: challengeDetailsData, status: responseStatus } = await topcoderApi.getChallenge(challenge.id)
  
}
```
Could you try to search by 'Message from challenge.notification.create: [{"id":"9ffff72c-ad6a-4c70-b0bf-ac52fd049558"'? 

2.Adding user. challengeID=30167490. This method is called to add User to a group. There are no payload  but  challengeID can be payload.challengeId or 'payload.id' (if it's called from createVanillaGroup) or payload.detail.challengeId depending topic:
```
2021-02-16T03:36:00.942-05:00	{ Error: cannot GET /api/v2/groups?access_token=removed&challengeID=30167490&page=1 (502)
```
Could you provide more lines before https://github.com/topcoder-platform/forums/issues/405#issuecomment-779677895?

502 Bad Gateway - another issue

3. "The group wasn't found"

When creating a new challenge, challenge forum processor almost immediately receives 'challenge.notification.create' + a list of 'challenge.action.resource.create' messages (one message per user).  It is impossible to process messages synchronously. 

The "The group wasn't found" message can only be displayed for Project members only because the group hasn't been created (or has been creating). When the group is created all Project members will be added by challenge processor.  Some details is mentioned https://github.com/topcoder-platform/forums/issues/229

When a new user (Submitter) registers for a challenge, then the group + all group categories have already been created.

**Comment by jmgasper** [comment]
@atelomycterus - Thanks for cleaning up the access token.  From @rootelement below - please have a look and let me know if it looks OK.  We can start to ignore the old events and focus on *just* the v5 ones.

> Pushed a fix to dev and prod to remove the v4 event listening from the challenge forum processor. That fixed a lot of the issues. I’m not seeing any forum create issues. I think the only issue now is challenges that were created that don’t have a forum. I’m going to see if I can put together an ES query to pull out discussions objects for draft/active challenges that don’t have a url
> 
> Ghostar  7:12 AM
> Ok, thanks
> 
> jcori:topcoder:  7:14 AM
> to be clear, this obviously wasn’t caused by the forum processsor. I believe that someone on another shapeup fixed the challenge.notification.events creator for another reason, and now the forum processor was getting inundated with out dated messages where the challenge id = the legacy id. those were unnecessary since the new forums are only created for challenges created in wm
> 7:15
> so, ultimately, this allowed us to quiet down the forum logs and the challenge api logs
> 7:15
> still debugging other issues

**Comment by jmgasper** [comment]
Challenge https://www.topcoder.com/challenges/fbc24f20-103c-41be-9406-534ceb1edb60 has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
Payment task has been updated: https://www.topcoder.com/challenges/fbc24f20-103c-41be-9406-534ceb1edb60
*Payments Complete*
Winner: obog
Copilot: ghostar
Challenge `fbc24f20-103c-41be-9406-534ceb1edb60` has been paid and closed.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by sdgun** [comment]
@atelomycterus Is there any impact of this fix and you want me to test specifically? OR should I test this one by creating a new challenge in production?

**Comment by atelomycterus** [comment]
@sdgun The issue was caused by the old events (v4).  See https://github.com/topcoder-platform/forums/issues/405#issuecomment-780096116. 

> Is there any impact of this fix and you want me to test specifically? OR should I test this one by creating a new challenge in production?

There were some changes in the code (https://github.com/topcoder-platform/challenge-forum-processor/commit/3dc65bd1d3fe5905653982281195bb1ab19fa8e6 by @ThomasKranitsas ). I don’t know if testing has already been done or not.

@jmgasper ☝️

**Comment by jmgasper** [comment]
@sdgun - Yes, you can test in production if you'd like, just to double check.

**Comment by sdgun** [comment]
Verified in Prod by creating new challenge https://www.topcoder.com/challenges/e678ec17-c72a-4e17-87fb-5082b7ae96bd. After registering the Challenge Discussions tab is displayed.

![image](https://user-images.githubusercontent.com/4592712/108458660-16073300-729b-11eb-8376-f9e31ad9899f.png)
