### ISSUE TITLE
[$50] Filestack plugin throws "Fatal Error in PHP.GuzzleHttp\choose_handler();" due to Guzzle Version Conflicts with two composer autoloader

### ISSUE THREAD

**Issue by atelomycterus** [topcoder-platform/forums#50]
Topcoder plugin and Filestack plugin depend on guzzleHttp libs. 
Filestack plugin throws a fatal error when trying to get an array of keys from the JWKS in Topcoder plugin.
Filestack plugin is disabled now.

```
vanilla-forums    | docker.vm:80 172.19.0.1 - - [28/Sep/2020:14:37:58 +0000] "GET / HTTP/1.1" 500 847 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
vanilla-forums    | [httpd:access] 127.0.0.1:80 - - 172.19.0.1 - - [28/Sep/2020:14:37:58 +0000] "GET / HTTP/1.1" 500 bytesIn:812 bytesOut:847 reqTime:0
vanilla-forums    | [28-Sep-2020 14:38:39] WARNING: [pool www] child 123 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\Utils::chooseHandler() in /vanillapp/plugins/Topcode
r/vendor/guzzlehttp/guzzle/src/functions.php:61"
vanilla-forums    | [28-Sep-2020 14:38:39] WARNING: [pool www] child 123 said into stderr: "Stack trace:"
vanilla-forums    | [28-Sep-2020 14:38:39] WARNING: [pool www] child 123 said into stderr: "#0 /vanillapp/plugins/Filestack/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\choose_handler()"
vanilla-forums    | [28-Sep-2020 14:38:39] WARNING: [pool www] child 123 said into stderr: "#1 /vanillapp/plugins/Filestack/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()"
vanilla-forums    | [28-Sep-2020 14:38:39] WARNING: [pool www] child 123 said into stderr: "#2 /vanillapp/plugins/Topcoder/vendor/auth0/auth0-php/src/API/Helpers/RequestBuilder.php(225): GuzzleHttp\Client->__construct(Array)"
vanilla-forums    | [28-Sep-2020 14:38:39] WARNING: [pool www] child 123 said into stderr: "#3 /vanillapp/plugins/Topcoder/vendor/auth0/auth0-php/src/Helpers/JWKFetcher.php(149): Auth0\SDK\API\Helpers\RequestBuilder->call()"
vanilla-forums    | [28-Sep-2020 14:38:39] WARNING: [pool www] child 123 said into stderr: "#4 /vanillapp/plugins/Topcoder/vendor/auth0/auth0-php/src/Helpers/JWKFetcher.php(111): Auth0\SDK\Helpers\JWKFetcher->requestJwks('https://topco
de...')"
vanilla-forums    | [28-Sep-2020 14:38:39] WARNING: [pool www] child 123 said into stderr: "#5 /vanillapp/plugins/Topcoder/class.topcoder.plugin.php(230): Auth0\SDK\Helpers\JWKFetcher->getKeys('https://topcode...')"
vanilla-forums    | [28-Sep-2020 14:38:39] WARNING: [pool www] child 123 said into stderr: "#6 [internal function]: TopcoderPlugin->gdn_auth_startA..."
vanilla-forums    | [php-fpm
```
![image](https://user-images.githubusercontent.com/10196632/94446905-e5224680-01b1-11eb-8e57-4886433d9af4.png)

**Comment by atelomycterus** [comment]
@jmgasper Fixed Guzzle Version Conflicts with two composer autoloader. 

**Developer Notes**
Filestack doesn't support Guzzle 7.0.
Topcoder plugin and Filestack plugins uses Guzzle ^6.2.

Added cache handler with expiration (24 hours, the same settings in https://github.com/appirio-tech/tc-core-library-js/blob/master/lib/auth/verifier.js#L25-L49).

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30143997 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30143997 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30143997<br/><br/>```This is an automated message for ghostar via Topcoder X```
