### ISSUE TITLE
[$150] Challenge forum processor debugging

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/forums#54]
@atelomycterus - I have got this configured and deployed in dev, and it's finally tied into everything.  I'm seeing a few issues

## Sample challenge create message

```[
    {
        "id": "b842a03b-ab00-4c19-a171-27ac3b74faeb",
        "created": "2020-09-29T22:25:38.666Z",
        "createdBy": "TonyJ",
        "updated": "2020-09-29T22:25:38.666Z",
        "updatedBy": "TonyJ",
        "status": "New",
        "projectId": 16604,
        "name": "Justin Forum Test 7",
        "typeId": "927abff4-7af9-4145-8ba1-577c16e64e2e",
        "trackId": "9b6fc876-f4d9-4ccb-9dfd-419247628825",
        "startDate": "2020-09-30T22:25:37.000Z",
        "legacy": {
            "reviewType": "community"
        },
        "descriptionFormat": "markdown",
        "timelineTemplateId": "6969125a-a12f-4b89-8de6-e66b0056f36b",
        "terms": [
            {
                "id": "b11da5cd-713f-478d-90f4-f679ef53ee95",
                "roleId": "732339e7-8e30-49d7-9198-cccf9451e221"
            }
        ],
        "phases": [
            {
                "duration": 259200,
                "phaseId": "a93544bc-c165-4af4-b55e-18f3593b457a",
                "id": "d7373dee-e2db-4a3a-a2de-56da494f0d99",
                "name": "Registration",
                "isOpen": false,
                "scheduledStartDate": "2020-10-01T08:25:37+10:00",
                "scheduledEndDate": "2020-10-03T22:25:37.000Z",
                "actualStartDate": "2020-10-01T08:25:37+10:00",
                "actualEndDate": "2020-10-03T22:25:37.000Z"
            },
            {
                "duration": 259200,
                "phaseId": "6950164f-3c5e-4bdc-abc8-22aaf5a1bd49",
                "id": "d7979cdf-d9bc-4bda-8655-c6a69792ba28",
                "name": "Submission",
                "isOpen": false,
                "predecessor": "d7373dee-e2db-4a3a-a2de-56da494f0d99",
                "scheduledStartDate": "2020-10-03T22:25:37.000Z",
                "scheduledEndDate": "2020-10-06T22:25:37.000Z",
                "actualStartDate": "2020-10-03T22:25:37.000Z",
                "actualEndDate": "2020-10-06T22:25:37.000Z"
            },
            {
                "duration": 172800,
                "phaseId": "aa5a3f78-79e0-4bf7-93ff-b11e8f5b398b",
                "id": "7c087fb4-f465-46ed-868c-c1f05f44a7b6",
                "name": "Review",
                "isOpen": false,
                "predecessor": "d7979cdf-d9bc-4bda-8655-c6a69792ba28",
                "scheduledStartDate": "2020-10-06T22:25:37.000Z",
                "scheduledEndDate": "2020-10-08T22:25:37.000Z",
                "actualStartDate": "2020-10-06T22:25:37.000Z",
                "actualEndDate": "2020-10-08T22:25:37.000Z"
            }
        ],
        "description": "",
        "groups": [
            
        ],
        "endDate": "2020-10-08T22:25:37.000Z",
        "numOfSubmissions": 0,
        "numOfRegistrants": 0,
        "currentPhaseNames": [
            
        ],
        "registrationStartDate": "2020-10-01T08:25:37+10:00",
        "registrationEndDate": "2020-10-03T22:25:37.000Z",
        "submissionStartDate": "2020-10-03T22:25:37.000Z",
        "submissionEndDate": "2020-10-06T22:25:37.000Z",
        "track": "Development",
        "type": "Challenge"
    }
]
```

## Issue 1

The group ID isn't coming back properly.  From the logs:

`2020-09-29T22:25:40.223Z [info]: The group with GroupID='undefined' for the challenge 'b842a03b-ab00-4c19-a171-27ac3b74faeb' is created`

## Issue 2

I see this error as well.  We may have to tweak the expectations around the setup, as Topcoder has changed the types and track values.

`2020-09-29T22:25:40.224Z [error]: Error: The default parent category for the challenge track 'Development' is not found
    at createVanillaGroup (/challenge-forum-processor/src/services/vanilla.js:110:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)`

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30144201 has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
Contest https://www.topcoder.com/challenges/30144201 has been updated - it has been assigned to obog.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by atelomycterus** [comment]
@jmgasper Fixed. Thanks for your email. It helps to understand where the bug was.  Please apply PRs:

https://github.com/topcoder-platform/challenge-forum-processor/pull/29
https://github.com/topcoder-platform/forums-plugins/pull/30
https://github.com/topcoder-platform/forums-groups-plugin/pull/7 

### Issue 1 - FIXED

Access token for /api should be validated by Vanilla, not Topcoder plugin. 

### Issue 2 - FIXED

Yes,  tracks have been changed. 

I noticed that the sample json doesn't  have 'prizeSets'. Tested in my local env:
![image](https://user-images.githubusercontent.com/10196632/94660732-be2d5700-030e-11eb-8d0d-e8b2d824c6c8.png)

### Additional issues 
Corrected typos in Groups.

**Comment by jmgasper** [comment]
@atelomycterus - I'm still seeing issues in the dev environment:

`2020-10-01T09:18:03.315Z [debug]: Message from challenge.notification.create: [{"id":"19a0c3cb-02b7-4f0a-a458-d3f202811a97","created":"2020-10-01T09:18:02.989Z","createdBy":"TonyJ","updated":"2020-10-01T09:18:02.989Z","updatedBy":"TonyJ","status":"New","projectId":16604,"name":"Justin Forum Test 10","typeId":"927abff4-7af9-4145-8ba1-577c16e64e2e","trackId":"9b6fc876-f4d9-4ccb-9dfd-419247628825","startDate":"2020-10-02T09:18:02.000Z","legacy":{"reviewType":"community"},"descriptionFormat":"markdown","timelineTemplateId":"6969125a-a12f-4b89-8de6-e66b0056f36b","terms":[{"id":"b11da5cd-713f-478d-90f4-f679ef53ee95","roleId":"732339e7-8e30-49d7-9198-cccf9451e221"}],"phases":[{"duration":259200,"phaseId":"a93544bc-c165-4af4-b55e-18f3593b457a","id":"782106b0-b053-419b-9a67-700bc231288b","name":"Registration","isOpen":false,"scheduledStartDate":"2020-10-02T19:18:02+10:00","scheduledEndDate":"2020-10-05T09:18:02.000Z","actualStartDate":"2020-10-02T19:18:02+10:00","actualEndDate":"2020-10-05T09:18:02.000Z"},{"duration":259200,"phaseId":"6950164f-3c5e-4bdc-abc8-22aaf5a1bd49","id":"7fd5d94a-b346-44bb-be18-1af5c93f16a4","name":"Submission","isOpen":false,"predecessor":"782106b0-b053-419b-9a67-700bc231288b","scheduledStartDate":"2020-10-05T09:18:02.000Z","scheduledEndDate":"2020-10-08T09:18:02.000Z","actualStartDate":"2020-10-05T09:18:02.000Z","actualEndDate":"2020-10-08T09:18:02.000Z"},{"duration":172800,"phaseId":"aa5a3f78-79e0-4bf7-93ff-b11e8f5b398b","id":"dcef7f00-84f4-48f2-9f0d-5d3515935f63","name":"Review","isOpen":false,"predecessor":"7fd5d94a-b346-44bb-be18-1af5c93f16a4","scheduledStartDate":"2020-10-08T09:18:02.000Z","scheduledEndDate":"2020-10-10T09:18:02.000Z","actualStartDate":"2020-10-08T09:18:02.000Z","actualEndDate":"2020-10-10T09:18:02.000Z"}],"discussions":[{"name":"Justin Forum Test 10 Discussion","type":"challenge","provider":"vanilla"}],"description":"","groups":[],"endDate":"2020-10-10T09:18:02.000Z","numOfSubmissions":0,"numOfRegistrants":0,"currentPhaseNames":[],"registrationStartDate":"2020-10-02T19:18:02+10:00","registrationEndDate":"2020-10-05T09:18:02.000Z","submissionStartDate":"2020-10-05T09:18:02.000Z","submissionEndDate":"2020-10-08T09:18:02.000Z","track":"Development","type":"Challenge"}]

2020-10-01T09:18:03.377Z [info]: The group with GroupID='undefined' for the challenge '19a0c3cb-02b7-4f0a-a458-d3f202811a97' is created

2020-10-01T09:18:03.617Z [info]: Announcement for the group 'undefined' is created

2020-10-01T09:18:03.669Z [info]: Discussion for the group 'undefined' is created`

**Comment by jmgasper** [comment]
I'm checking with Topcoder as well to make sure the deployment is working properly.

**Comment by atelomycterus** [comment]
@jmgasper 
The group with GroupID='undefined'  because  Vanilla responses with error html page. 
I fixed it yesterday (https://github.com/topcoder-platform/forums-plugins/commit/ccf37803eebee96be34d6d641f4d6c75378fdcfb#diff-2e35cd35eec28b023b87f4e9949e45e6).
Topcoder plugin ignores /api endpoints. Vanilla checks access_token for /api.

I'll re-test it on vanilla.topcoder-dev.com

 https://github.com/topcoder-platform/forums-plugins/blob/master/Topcoder/class.topcoder.plugin.php#L213

```
        // Ignore EntryController endpoints and ApiController endpoints.
        // AccessToken for /api will be checked in class.hooks.php
        if (stringBeginsWith(Gdn::request()->getPath(), '/api/') || stringBeginsWith(Gdn::request()->getPath(), '/entry/')) {
            return;
        }
```

**Comment by atelomycterus** [comment]
@jmgasper I see the issue in vanilla.topcoder-dev. com.  
```
return request.post(`${config.VANILLA.API_URL}/groups`)
        .query({ access_token: config.VANILLA.ADMIN_ACCESS_TOKEN })
        .send(data)
```
Vanilla returns a list of groups but it should be one group added.

/Api works fine. If not Topcoder token , we can use /api  with Vanilla token:
https://vanilla.topcoder-dev.com/api/v2/groups?access_token=XXXX
![image](https://user-images.githubusercontent.com/10196632/94804064-e8584500-03f2-11eb-90ad-bff3d59574a0.png)

**Comment by atelomycterus** [comment]
@jmgasper Please check your default.js (challenge-forum-processor/config/default.js). It should be 'https', not 'http'
API_URL: process.env.VANILLA_API_URL || "https://vanilla.topcoder-dev.com/api/v2",

I tested  it and  it works.
![image](https://user-images.githubusercontent.com/10196632/94817908-31fe5b00-0406-11eb-82dc-8bf24e615bab.png)

**Comment by jmgasper** [comment]
@atelomycterus - Thanks.  I'm working with Topcoder to validate to make sure it's set up correctly in the dev environment.

**Comment by jmgasper** [comment]
@atelomycterus - That was the issue, thanks!  Updated that and everything's working.

**Comment by jmgasper** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30144201<br/><br/>```This is an automated message for ghostar via Topcoder X```
